FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm@10.15.0 && \
    pnpm config set store-dir /pnpm/store






FROM base AS deps
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/network/server/package.json ./apps/network/server/package.json

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --frozen-lockfile








FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/network/server/node_modules ./apps/network/server/node_modules
COPY . .

WORKDIR /app/apps/network/server
RUN pnpm exec prisma generate && \
    pnpm build

WORKDIR /app
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --prod --frozen-lockfile --ignore-scripts





FROM node:20-alpine AS production
WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache openssl && \
    addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nestjs

COPY --from=builder --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/apps/network/server/node_modules ./apps/network/server/node_modules
COPY --from=builder --chown=nestjs:nodejs /app/apps/network/server/dist ./apps/network/server/dist
COPY --from=builder --chown=nestjs:nodejs /app/apps/network/server/package.json ./apps/network/server/package.json
COPY --from=builder --chown=nestjs:nodejs /app/apps/network/server/prisma ./apps/network/server/prisma
COPY --from=builder --chown=nestjs:nodejs /app/apps/network/server/prisma.config.cjs ./apps/network/server/prisma.config.cjs

USER nestjs
CMD ["node", "apps/network/server/dist/src/main.js"]