export enum RelationshipStatus {
	BLOCKED_BY_YOU = 'BLOCKED_BY_YOU',
	BLOCKED_BY_THEM = 'BLOCKED_BY_THEM',
	MUTUAL_BLOCK = 'MUTUAL_BLOCK',

	FRIENDS = 'FRIENDS',
	REQUEST_SENT = 'REQUEST_SENT',
	REQUEST_RECEIVED = 'REQUEST_RECEIVED',

	NONE = 'NONE',
}
